from aiogram import F
from aiogram.filters import CommandStart, Command
from aiogram.types import Message, CallbackQuery, InlineKeyboardMarkup, InlineKeyboardButton
from aiogram.enums.parse_mode import ParseMode
from loguru import logger
from .dispatcher import dp, bot, ADMIN_IDS
from . import db

# Reuse all logic from the previous bot.py but relying on imported dp/bot/ADMIN_IDS
# To keep the patch concise, we import functions by referencing the existing file.
from .bot import (
    main_menu,
    _send_whoami,
    _send_list_users,
    _send_list_routes,
    _send_manage,
    _send_aliases,
    _myteam_menu,
    _send_myteam,
    cb_myteam_list,
    cb_myteam_add,
    cb_myteam_remove,
    cb_myteam_remove_user,
    _teams_menu,
    _send_teams,
    cb_teams_list,
    cb_team_new,
    cb_team_setlead,
    cb_team_choose_for_lead,
    cb_team_members,
    cb_team_members_manage,
    cb_team_add_member,
    cb_team_remove_member,
    on_menu,
    on_menu_click,
    on_start,
    on_help,
    on_ping,
    on_whoami,
    on_list_users,
    _user_row_controls,
    on_manage,
    alias_row_controls,
    on_aliases,
    _mentor_row_controls,
    _mentor_add_controls,
    _send_mentors,
    _mentor_subs_keyboard,
    cb_mentor_add,
    cb_mentor_unset,
    cb_mentor_subs,
    cb_mentor_toggle,
    cb_mentor_back,
    on_setalias,
    on_delalias,
    cb_alias_new,
    cb_alias_setbuyer,
    cb_alias_setlead,
    cb_alias_delete,
    cb_team_choose,
    cb_team_set,
    on_text_fallback,
    cb_set_role,
    cb_set_active,
    on_list_routes,
    on_add_rule,
    on_set_role,
    on_create_team,
    on_set_team,
    on_list_teams,
    notify_buyer,
    _reports_menu,
    _send_reports_menu,
    _resolve_scope_user_ids,
    _report_text,
    _send_period_report,
    cb_report_today,
    cb_report_yesterday,
    cb_report_week,
    on_today,
    on_yesterday,
    on_week,
    cb_report_filter,
    cb_report_clear_chip,
    _teams_picker_kb,
    _buyers_picker_kb,
    _offers_picker_kb,
    _creatives_picker_kb,
    cb_report_pick_team,
    cb_report_pick_buyer,
    cb_report_pick_offer,
    cb_report_pick_creative,
    cb_report_set_filter_quick,
    _kpi_menu,
    _send_kpi_menu,
    cb_kpi_mine,
    cb_kpi_set,
    on_add_mentor,
    on_mentor_follow,
    on_mentor_unfollow,
)
